[package]
name = "zx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.30.1"
log = "0.4.14"
env_logger = "0.8.4"
itertools = "0.10.3"
pretty_assertions = "1.1.0"
rand = "0.8.4"
rayon = "1.5.1"

[dev-dependencies]
test-log = "0.2.8"