[package]
name = "bra_ket"
description = "A multithreaded circuit model quanutm simulator for state vectors and density matricies."
license = "MIT"
readme = "README.md"
repository = "https://github.com/b-vanstraaten/bra_ket"
keywords = ["quantum", "simulator", "circuit", "state", "density"]
categories = ["science", "simulation"]

version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.30.1"
log = "0.4.14"
itertools = "0.10.3"
rayon = "1.5.1"
rand = "0.8.5"
textplots = "0.6"

[dev-dependencies]
