[package]
name = "bra_ket"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.30.1"
log = "0.4.14"
itertools = "0.10.3"
rayon = "1.5.1"
rand = "0.8.5"
textplots = "0.6"


[dev-dependencies]
