[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
syn = "1.0.89"
quote = "1.0.16"
nalgebra = "0.30.1"
proc-macro2 = "1.0.36"

simulator = {path = "../simulator"}
